#!/usr/bin/perl

$obfuscate = 1;

$regexp = shift;
$continue = 0;
while (<>) {
  if ($_ =~ /$regexp/) {
   if ($obfuscate) {
      $line = $_;
      $line =~ s/\d+\.\d+\.(\d+\.\d+)/XXX.XXX.\1/g;
      $line =~ s/\.gpn\.gov\.uk/.XXX.XXX.XXX/gi;
      print $line;
    } else {
      print $_;
    }
    $continue = 1;
  } else {
    unless (/^[0-9A-F]{8} \d\d:\d\d:\d\d\.\d\d\d /) {
      if ($continue) {
        if ($obfuscate) {
          $line = $_;
          $line =~ s/\d+\.\d+\.(\d+\.\d+)/XXX.XXX.\1/g;
          $line =~ s/\.gpn\.gov\.uk/.XXX.XXX.XXX/gi;
          print $line;
        } else {
          print $_;
        }
      }
    } else {
      $continue = 0;
    }
  }
}
